### ISSUE TITLE
.json output doesn't contain keys

### ISSUE THREAD

**Issue by metafarion** [javierjulio/humble-bundle-key-exporter#348]
Am I missing something?  The .json file I get as output has a complete list of unredeemed games... but without any actual steam keys.  Example:

  {
    "platform": "Steam",
    "name": "Brothers: A Tale of Two Sons",
    "bundle": "Stand with Ukraine Bundle",
    "bundle_url": "https://www.humblebundle.com/download?key=HFwBnDeHPy7uWDMr"
  },

**Comment by javierjulio** [comment]
No but I can see now how it's confusing. Sorry about that. It's not meant to have the raw keys themselves but the URL to the page where you would get it. I'll look into updating the README and description so that's clearer.

I built this tool so I could easily get a list of everything I had that was unredeemed so I could share with friends to see if anything they wanted.

Funny coincidence seeing your profile photo as I've been playing SC Remastered today!

**Comment by metafarion** [comment]
OHHH, ok, yeah I guess I didn't quite get the purpose of the tool since it scrapes the pages that would have the actual keys on them if the Redeem buttons were clicked.

**Comment by javierjulio** [comment]
No, not quite. It parses the page but **only where it lists the unredeemed keys**. The script will check the option labeled "Hide redeemed keys & entitlements" before scraping. So the script wouldn't ever see any keys on the page since none have been redeemed. Hence why it returns the bundle URL for each so it's easy to get too.
